import port2 from '../img/portImages/port1.jpg';
import sortVis from '../img/portImages/sortVis.png';

// Portfolio Categories:
// 1. Web
// 2. Python
// 3. iOS

const portfolios = [
  {
    id: 1,
    category: 'Web',
    link1: 'https://aqueous-escarpment-60789.herokuapp.com/',
    link2: 'https://github.com/Karsenh/SortingVisualizer/',
    icon1: 'View',
    icon2: 'GitHub',
    image: sortVis,
    title: 'Sorting Visualizer',
    description: 'React.js visualizer for JS sorting algorithms.',
  },
  {
    id: 2,
    category: 'iOS',
    link1: '',
    link2: 'https://www.github.com/Karsenh/Clima-for-iOS',
    icon1: 'View',
    icon2: 'GitHub',
    image: port2,
    title: 'Clima',
    description: 'Swift based weather app for iOS',
  },
  {
    id: 3,
    category: 'iOS',
    link1: '',
    link2: '',
    icon1: 'View',
    icon2: 'GitHub',
    image: port2,
    title: 'Dicee (iOS)',
    description: 'Swift based dice game for iOS',
  },
  {
    id: 4,
    category: 'iOS',
    link1: '',
    link2: '',
    icon1: 'View',
    icon2: 'GitHub',
    image: port2,
    title: 'Magic 8 Ball',
    description: 'Swift based 8-Ball game for iOS',
  },
  {
    id: 5,
    category: 'iOS',
    link1: '',
    link2: '',
    icon1: 'View',
    icon2: 'GitHub',
    image: port2,
    title: 'Egg Timer',
    description: 'Swift based Egg Timer app for iOS',
  },
  {
    id: 6,
    category: 'iOS',
    link1: '',
    link2: '',
    icon1: 'View',
    icon2: 'GitHub',
    image: port2,
    title: 'Quizzler',
    description: 'Swift based quiz game for iOS',
  },
  {
    id: 7,
    category: 'iOS',
    link1: '',
    link2: '',
    icon1: 'View',
    icon2: 'GitHub',
    image: port2,
    title: 'Text-Adventure',
    description: 'Swift based text adventure game for iOS',
  },
  {
    id: 8,
    category: 'iOS',
    link1: '',
    link2: '',
    icon1: 'View',
    icon2: 'GitHub',
    image: port2,
    title: 'BMI Calculator',
    description: 'Swift based body-mass-index calculator for iOS',
  },
  {
    id: 9,
    category: 'iOS',
    link1: '',
    link2: '',
    icon1: 'View',
    icon2: 'GitHub',
    image: port2,
    title: 'Tip Calculator',
    description: 'Swift based calculator for tip splits on iOS',
  },
  {
    id: 10,
    category: 'Web',
    link1: '',
    link2: '',
    icon1: 'View',
    icon2: 'GitHub',
    image: port2,
    title: 'Dicee (Web)',
    description: 'Simple JS dice game for browser',
  },
  {
    id: 11,
    category: 'Web',
    link1: '',
    link2: '',
    icon1: 'View',
    icon2: 'GitHub',
    image: port2,
    title: 'Interactive Drums',
    description: 'JS interactive drum kit',
  },
  {
    id: 12,
    category: 'Web',
    link1: '',
    link2: '',
    icon1: 'View',
    icon2: 'GitHub',
    image: port2,
    title: 'Simon',
    description: 'JS Simon-says style game for browser',
  },
  {
    id: 13,
    category: 'Web',
    link1: '',
    link2: '',
    icon1: 'View',
    icon2: 'GitHub',
    image: port2,
    title: 'To-Do',
    description: 'Simple EJS based Blog for browser',
  },
  {
    id: 14,
    category: 'Web',
    link1: '',
    link2: '',
    icon1: 'View',
    icon2: 'GitHub',
    image: port2,
    title: 'Secret',
    description: 'Node based user auth via Passport & OAuth',
  },
  {
    id: 15,
    category: 'Web',
    link1: '',
    link2: '',
    icon1: 'View',
    icon2: 'GitHub',
    image: port2,
    title: 'To-Do (Auth)',
    description: 'MEAN-stack To-Do list with user authentication',
  },
  {
    id: 16,
    category: 'Web',
    link1: '',
    link2: '',
    icon1: 'View',
    icon2: 'GitHub',
    image: port2,
    title: 'Keeper',
    description: 'React based Google Keep style app',
  },
];

export default portfolios;
